export const SET_PROFILE = 'SET_PROFILE';
export const CLEAN_PROFILE = 'CLEAN_PROFILE';
export const SET_FAMILY = 'SET_FAMILY';
export const CLEAN_FAMILY = 'CLEAN_FAMILY';
export const SET_MEDICAL_HISTORY = 'SET_MEDICAL_HISTORY';
export const CLEAN_MEDICAL_HISTORY = 'CLEAN_MEDICAL_HISTORY';
export const SET_SCREENS = 'SET_SCREENS';
export const CLEAN_SCREENS = 'CLEAN_SCREENS';
